apiVersion: v2
name: appointment-app
description: Helm chart for Appointment App
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: prometheus
    version: "15.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "6.56.6"
    repository: "https://grafana.github.io/helm-charts"
