replicaCount: 2

image:
  repository: 850995567750.dkr.ecr.us-east-1.amazonaws.com/appointment-app
  tag: ""   # On laisse vide ici, car on passe le tag dans le workflow via --set

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

mail:
  service: "gmail"
  user: ""  # Ces valeurs seront inject√©es par Helm via le workflow
  pass: ""
  to: ""

mongodb:
  enabled: true
  auth:
    rootPassword: "appointmentAppRoot"
    username: "appointmentApp"
    password: "appointmentAppPass"
    database: "appointments"

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

grafana:
  enabled: true
  adminPassword: "admin"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    - configMapName: appointment-app-dashboard
      fileName: appointment-dashboard.json
