apiVersion: v1
kind: Secret
metadata:
  name: appointment-mail
type: Opaque
stringData:
  MAIL_SERVICE: "{{ .Values.mail.service }}"
  MAIL_USER: "{{ .Values.mail.user }}"
  MAIL_PASS: "{{ .Values.mail.pass }}"
  MAIL_TO: "{{ .Values.mail.to }}"
