apiVersion: v1
kind: Service
metadata:
  name: appointment-app
spec:
  selector:
    app: appointment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: {{ .Values.service.type }}
